// <auto-generated />
namespace WebBanHang.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update2310 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update2310));
        
        string IMigrationMetadata.Id
        {
            get { return "202310231031592_update2310"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
